### PR TITLE
BugFix and features added to the node_orchestrator plugin.

### PR DESCRIPTION
**Pull request by ivanocerrato**
The node_orchestator plugin no longer needs a configuration file.
A message exchanged between the node orchestator has been changed. 
A bug has been fixed.

### CODE REVIEW

**Comment by msune** [comment]
Missing libjson-spirit check in `configure.ac`. I am working on a patch for that. So that you can add it to the PR.

**Comment by msune** [comment]
So adding the check and trying to compile the plugin node_orchestrator against Debian8 package `libjson-spirit-dev` fails very badly:

```
marc@dev:~/git/bisdn/xdpd/build$ git diff
diff --git a/config/plugin_node_orchestrator.m4 b/config/plugin_node_orchestrator.m4
index 37dcb85..3aef26b 100644
--- a/config/plugin_node_orchestrator.m4
+++ b/config/plugin_node_orchestrator.m4
@@ -2,8 +2,11 @@
 AM_CONDITIONAL([WITH_MGMT_NODE_ORCHESTRATOR], true)
 AC_DEFINE(WITH_MGMT_NODE_ORCHESTRATOR)

-#LIB checks e.g.
-#AC_CHECK_LIB(pthread, pthread_kill,,AC_MSG_ERROR([pthread library not found])) 
+#Check for json-spirit
+AC_LANG_PUSH([C++])
+AC_CHECK_HEADERS([json_spirit.h], [],
+       [AC_ERROR([Cannot find required libjson-spirit. Please install it.])], [])
+AC_LANG_POP([C++])

 #Add files
 AC_CONFIG_FILES([
diff --git a/src/xdpd/management/plugins/node_orchestrator/message_handler.h b/src/xdpd/management/plugins/node_orchestrator/message_handler.h
index 9759187..c032660 100644
--- a/src/xdpd/management/plugins/node_orchestrator/message_handler.h
+++ b/src/xdpd/management/plugins/node_orchestrator/message_handler.h
@@ -3,12 +3,12 @@

 #pragma once

-#include <json_spirit/json_spirit.h>
-#include <json_spirit/writer.h>
-#include <json_spirit/reader.h>
-#include <json_spirit/reader_template.h>
-#include <json_spirit/writer_template.h>
-#include <json_spirit/value.h>
+#include <json_spirit.h>
+#include <json_spirit_writer.h>
+#include <json_spirit_reader.h>
+#include <json_spirit_reader_template.h>
+#include <json_spirit_writer_template.h>
+#include <json_spirit_value.h>

 #include <string>
 #include <sstream>
```

Just a part of the errors[1]:

So my proposal would be the following, taking into account 0.7;

1) For 0.6 you specify the requirements in your plugin in a `README-node-orchestrator.md`, pointing to the github repository where lays the "right" version for the current code. We don't do further checks
2) Since 0.7 is coming in very few days, we should unify the rest and the node_orchestrator to use the same `libjson_spirit`:

https://github.com/bisdn/xdpd/tree/integration-0.7/src/xdpd/management/plugins/rest/json_spirit

We are deliberately compiling it anyway onboard due to the problems with versions and packages 

[1]

```
Making all in src
make[1]: Entering directory '/home/marc/git/bisdn/xdpd/build/src'
Making all in xdpd
make[2]: Entering directory '/home/marc/git/bisdn/xdpd/build/src/xdpd'
Making all in management
make[3]: Entering directory '/home/marc/git/bisdn/xdpd/build/src/xdpd/management'
Making all in plugins
make[4]: Entering directory '/home/marc/git/bisdn/xdpd/build/src/xdpd/management/plugins'
Making all in node_orchestrator
make[5]: Entering directory '/home/marc/git/bisdn/xdpd/build/src/xdpd/management/plugins/node_orchestrator'
  CXX      node_orchestrator.lo
  CXX      message_handler.lo
../../../../../../src/xdpd/management/plugins/node_orchestrator/node_orchestrator.cc: In static member function 'static std::pair<unsigned int, unsigned int> xdpd::NodeOrchestrator::createVirtualLink(uint64_t, uint64_t)':
../../../../../../src/xdpd/management/plugins/node_orchestrator/node_orchestrator.cc:204:74: error: no matching function for call to 'xdpd::port_manager::connect_switches(uint64_t&, std::string&, uint64_t&, std::string&)'
   port_manager::connect_switches(dpid_a, name_port_a, dpid_b, name_port_b);
                                                                          ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/node_orchestrator.cc:204:74: note: candidate is:
In file included from ../../../../../../src/xdpd/management/plugins/node_orchestrator/node_orchestrator.h:7:0,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/node_orchestrator.cc:1:
../../../../../../src/xdpd/management/plugins/node_orchestrator/../../port_manager.h:147:14: note: static void xdpd::port_manager::connect_switches(uint64_t, unsigned int*, std::string&, uint64_t, unsigned int*, std::string&)
  static void connect_switches(uint64_t dpid_lsi1, unsigned int* port_num1, std::string& port_name1, uint64_t dpid_lsi2, unsigned int* port_num2, std::string& port_name2);
              ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/../../port_manager.h:147:14: note:   candidate expects 6 arguments, 4 provided
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc: In static member function 'static std::string xdpd::MessageHandler::processCommand(std::string)':
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:58:21: error: 'json_spirit::Value' has no member named 'getObject'
  Object obj = value.getObject();
                     ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:62:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'first'
         const string& name  = i->first;
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:63:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'second'
         const Value&  value = i->second;
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:67:33: error: 'const Value' has no member named 'getString'
          string command = value.getString();
                                 ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc: In static member function 'static std::string xdpd::MessageHandler::createLSI(std::string)':
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:116:21: error: 'json_spirit::Value' has no member named 'getObject'
  Object obj = value.getObject();
                     ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:120:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'first'
         const string& name  = i->first;
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:121:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'second'
         const Value&  value = i->second;
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:129:35: error: 'const Value' has no member named 'getObject'
         Object controller = value.getObject();  
                                   ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:132:32: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'first'
     const string& c_name  = j->first;
                                ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:133:32: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'second'
     const Value&  c_value = j->second;
                                ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:137:36: error: 'const Value' has no member named 'getString'
      controllerAddress += (c_value.getString());
                                    ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:142:33: error: 'const Value' has no member named 'getString'
      controllerPort += (c_value.getString());
                                 ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:149:37: error: 'const Value' has no member named 'getArray'
    const Array& ports_array = value.getArray();
                                     ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:152:45: error: 'const class json_spirit::Value_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'getString'
     physicalPorts.push_back( ports_array[i].getString() );
                                             ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:158:31: error: 'const Value' has no member named 'getString'
          wirelessPort = value.getString();
                               ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:162:35: error: 'const Value' has no member named 'getArray'
    const Array& nfs_array = value.getArray();
                                   ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:166:31: error: 'const class json_spirit::Value_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'getObject'
     Object nfs = nfs_array[i].getObject();
                               ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:177:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'first'
      const string& nf_name  = j->first;
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:178:34: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'second'
      const Value&  nf_value = j->second; 
                                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:182:23: error: 'const Value' has no member named 'getString'
       name = nf_value.getString();
                       ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:187:29: error: 'const Value' has no member named 'getString'
       string tmp = nf_value.getString();
                             ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:199:43: error: 'const Value' has no member named 'getArray'
       const Array& ports_array = nf_value.getArray();
                                           ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:202:40: error: 'const class json_spirit::Value_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'getString'
        ports.push_back( ports_array[i].getString() );
                                        ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:221:39: error: 'const Value' has no member named 'getObject'
          Object virtual_links = value.getObject();
                                       ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:227:32: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'first'
     const string& c_name  = j->first;
                                ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:228:32: error: 'const struct json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' has no member named 'second'
     const Value&  c_value = j->second;
                                ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:232:30: error: 'const Value' has no member named 'getInt'
      vlinks_number = c_value.getInt();
                              ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:237:35: error: 'const Value' has no member named 'getInt'
      vlinks_remote_dpid = c_value.getInt(); //FIXME: the dpid is actually a uint64_t
                                   ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc: In static member function 'static std::string xdpd::MessageHandler::createLSIAnswer(xdpd::LSI, std::map<std::basic_string<char>, std::map<std::basic_string<char>, unsigned int> >, std::list<std::pair<unsigned int, unsigned int> >, bool, unsigned int)':
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:339:16: error: invalid conversion from 'const char*' to 'std::vector<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >, std::allocator<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > > > >::size_type {aka long unsigned int}' [-fpermissive]
  json["command"] = CREATE_LSI;
                ^
In file included from /usr/include/c++/4.9/vector:64:0,
                 from /usr/include/json_spirit_value.h:13,
                 from /usr/include/json_spirit.h:13,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.h:6,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:1:
/usr/include/c++/4.9/bits/stl_vector.h:779:7: note: initializing argument 1 of 'std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >; _Alloc = std::allocator<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > > >; std::vector<_Tp, _Alloc>::reference = json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'
       operator[](size_type __n) _GLIBCXX_NOEXCEPT
       ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:339:18: error: no match for 'operator=' (operand types are 'json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' and 'const char [11]')
  json["command"] = CREATE_LSI;
                  ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:339:18: note: candidate is:
In file included from /usr/include/json_spirit.h:13:0,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.h:6,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:1:
/usr/include/json_spirit_value.h:128:12: note: json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >& json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >::operator=(const json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&)
     struct Pair_impl
            ^
/usr/include/json_spirit_value.h:128:12: note:   no known conversion for argument 1 from 'const char [11]' to 'const json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&'
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:340:15: error: invalid conversion from 'const char*' to 'std::vector<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >, std::allocator<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > > > >::size_type {aka long unsigned int}' [-fpermissive]
  json["status"] = "ok"; 
               ^
In file included from /usr/include/c++/4.9/vector:64:0,
                 from /usr/include/json_spirit_value.h:13,
                 from /usr/include/json_spirit.h:13,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.h:6,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:1:
/usr/include/c++/4.9/bits/stl_vector.h:779:7: note: initializing argument 1 of 'std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >; _Alloc = std::allocator<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > > >; std::vector<_Tp, _Alloc>::reference = json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'
       operator[](size_type __n) _GLIBCXX_NOEXCEPT
       ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:340:17: error: no match for 'operator=' (operand types are 'json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >' and 'const char [3]')
  json["status"] = "ok"; 
                 ^
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:340:17: note: candidate is:
In file included from /usr/include/json_spirit.h:13:0,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.h:6,
                 from ../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:1:
/usr/include/json_spirit_value.h:128:12: note: json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >& json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >::operator=(const json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&)
     struct Pair_impl
            ^
/usr/include/json_spirit_value.h:128:12: note:   no known conversion for argument 1 from 'const char [3]' to 'const json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >&'
../../../../../../src/xdpd/management/plugins/node_orchestrator/message_handler.cc:342:15: error: invalid conversion from 'const char*' to 'std::vector<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > >, std::allocator<json_spirit::Pair_impl<json_spirit::Config_vector<std::basic_string<char> > > > >::size_type {aka long unsigned int}' [-fpermissive]
  json["lsi-id"] = lsi.getDpid();
               ^

```

**Comment by msune** [comment]
If you agree. Just add the required `README` following the style of:

https://github.com/bisdn/xdpd/blob/stable-0.6/README-conf-file.md

And we merge this. For 0.7 I will have a look how to make it compile.

**Comment by ivanocerrato** [comment]
Added the REAME-node-orchestrator.md file.

**Comment by ivanocerrato** [comment]
Done

**Comment by msune** [comment]
ACK

**Comment by ivanocerrato** [comment]
Tested and works. ACK

**Pull request merged**
