### PR TITLE
integrated updates

### PR DESCRIPTION
**Pull request by toanju**
adding a lot of updates to stable including
* stable-0.7 branch
* rofl-common latest
* rofl-datapath latest
* dpdk latest

### CODE REVIEW

**Comment by toanju** [comment]
this includes as well #107

**Comment by butjar** [comment]
It's huge ... LGTM

**Comment by toanju** [comment]
Basically the in tree build failed with dpdk 16.11. Hence I aligned the build process using the output directory (O=dir) switch of dpdk.

**Comment by hwoesner** [comment]
Tobi was standing behind me with a gun in his hand.
The current xdpd is tested in different setups with and without DPDK and with ryu-test, so I believe it is safe to merge.

**Comment by butjar** [comment]
:ship:

**Comment by toanju** [comment]
:gun: :smiling_imp:

**Pull request merged**
